OBJ=		objects
SRC=		src
BIN=		bin
HEADER=		include
CCFLAGS=	-Wall -O2 -g -static -fno-strict-aliasing -I $(HEADER)
CC=			arm-unknown-linux-gnu-gcc

default:
	make $(BIN)/gb4gp2x
	
$(BIN)/gb4gp2x: $(OBJ)/opcodes.o $(OBJ)/proc.o $(SRC)/boot.c
	$(CC) $(CCFLAGS) -o $@ $^
	
$(OBJ)/proc.o: $(SRC)/proc.c
	$(CC) $(CCFLAGS) -c -o $@ $^

$(OBJ)/opcodes.o: $(SRC)/opcodes.c
	$(CC) $(CCFLAGS) -c -o $@ $^

install: $(BIN)/gb4gp2x
	ln -sf ./$(BIN)/gb4gp2x ./gb

clean:
	rm -f $(OBJ)/*o
	rm -f $(BIN)/*
